Repository cucumber/language-service, pull requests merged in 2024-04, with the labels that each got.

#196 Index failure with partial Python parameter match
  CHANGELOG.md
  src/language/pythonLanguage.ts
  test/language/testdata/python/ParameterTypes.py
Labels: :bug: bug

#130 Go step definitions support
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  scripts/build.js
  src/language/goLanguage.ts
  src/language/helpers.ts
  src/language/languages.ts
  src/language/phpLanguage.ts
  src/language/types.ts
  src/service/getGenerateSnippetCodeAction.ts
  src/tree-sitter-node/NodeParserAdapter.ts
  test/language/goLanguage.test.ts
  test/language/testdata/go/StepDefinitions.go
Labels: :zap: enhancement

#200 Behave generic step definition decorator
  CHANGELOG.md
  src/language/pythonLanguage.ts
  test/language/testdata/python/StepDefinitions.py
Labels: :zap: enhancement

#197 Improve Python language support code
  TODO.md
  src/language/pythonLanguage.ts
Labels: :bank: debt

#202 fix: java concatenated strings in definitions and generic decorators
  CHANGELOG.md
  src/language/javaLanguage.ts
  test/language/testdata/java/StepDefinitions.java
  test/language/testdata/python/StepDefinitions.py
Labels: :bug: bug
