Repository cucumber/language-service, pull requests merged in 2024-07, with the labels that each got.

#215 Fix: Find godog step definitions within `method_declaration`
  CHANGELOG.md
  src/language/goLanguage.ts
  test/language/ExpressionBuilder.test.ts
  test/language/testdata/go/StepDefinitions.go
  test/language/testdata/php/StepDefinitions.php
Labels: :bug: bug

#219 fix: parameter highlighting for outline steps with leading spaces
  CHANGELOG.md
  src/service/getGherkinSemanticTokens.ts
  test/service/getGherkinSemanticTokens.test.ts
Labels: :bug: bug

#222 Compiled cjs step definitions
  CHANGELOG.md
  src/language/javascriptLanguage.ts
  test/language/ExpressionBuilder.test.ts
  test/language/testdata/javascript/StepDefinitions.js
Labels: :zap: enhancement

#226 chore(deps): update dependency tree-sitter-rust to v0.20.4
  package-lock.json
  package.json
  src/language/rustLanguage.ts
Labels: :robot: dependencies

#227 Expose all build suggestion APIs in `index.ts`
  CHANGELOG.md
  src/suggestions/index.ts
Labels: :zap: enhancement
